sudo: required

services:
  - docker

before_install:
  - docker build -t franzbewerunge/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true franzbewerunge/react-tests npm test

after_success:
  - docker build -t franzbewerunge/multi-client ./client
  - docker build -t franzbewerunge/multi-nginx ./nginx
  - docker build -t franzbewerunge/multi-server ./server
  - docker build -t franzbewerunge/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push franzbewerunge/multi-client 
  - docker push franzbewerunge/multi-nginx 
  - docker push franzbewerunge/multi-server 
  - docker push franzbewerunge/multi-worker 
